### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by kgryte** [math-io/frexp#1]
Depends on math-io/float64-exponent#1 and math-io/float64-from-words#1.

**Comment by kgryte** [comment]
We should probably also rename this module as `float64-frexp`.

**Comment by kgryte** [comment]
Updated deps.

**Comment by Planeshifter** [comment]
Looks all well to me. One comment: I would refrain from using modules like `const-ninf-float64` in example code. These modules hide native JS values, and without reading the source code it might not be clear for a third-party what these constants represent.

**Comment by kgryte** [comment]
Point taken. Without comments, `ninf` and `pinf` are opaque. The main reason for using these modules is to distinguish from `const-ninf-float32`, etc. I suppose for the purposes of example code, using `Number.POSITIVE_INFINITY`, etc, for built-in constants is fine, but not so for underlying implementations where constant type matters and should be explicit.

Will update the `README` before publishing.

**Comment by kgryte** [comment]
Updated.
